apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golist-deals
  name: golist-deals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golist-deals
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golist-deals
    spec:
      containers:
      - image: quay.io/christianh814/golist-deals:latest
        name: golist-deals
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        volumeMounts:
        - name: config-volume
          mountPath: /opt/app-root/src/appconfig
        resources: {}
      volumes:
        - name: config-volume
          configMap:
            name: golist-deals-config
